app/views/restaurant.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for
from app.decorators import login_required
from app import db
import pdb

mod_restaurant = Blueprint('restaurants', __name__, url_prefix='/restaurants', template_folder='templates' )

@mod_restaurant.route('/main')
@login_required
def main():
    return render_template('restaurants/main.html')

@mod_restaurant.route('/', methods = ['GET', 'POST'])
@login_required
def index():
    if request.method == "POST":
        sort_type= request.form.get('sort_type')
        method= request.form.get('method')
        if sort_type == "customer number":
            if method == "DESC":
                cur = db.engine.execute("SELECT r.restaurant_id, r.name, AVG(w.unlisted_at - w.listed_at) AS avg_waiting, COUNT (w.customer_id) As avg_customer FROM restaurant r LEFT JOIN waitlist w ON r.restaurant_id = w.restaurant_id GROUP BY r.restaurant_id ORDER BY avg_customer DESC")
            elif method == "ASC":
                cur = db.engine.execute("SELECT r.restaurant_id, r.name, AVG(w.unlisted_at - w.listed_at) AS avg_waiting, COUNT (w.customer_id) As avg_customer FROM restaurant r LEFT JOIN waitlist w ON r.restaurant_id = w.restaurant_id GROUP BY r.restaurant_id ORDER BY avg_customer ASC")
            rows = cur.fetchall();
        if sort_type == "waiting time":
            if method == "DESC":
                st = "SELECT r.restaurant_id, r.name, AVG(w.unlisted_at - w.listed_at) AS avg_waiting, COUNT (w.customer_id) As avg_customer FROM restaurant r LEFT JOIN waitlist w ON r.restaurant_id = w.restaurant_id GROUP BY r.restaurant_id ORDER BY avg_waiting DESC"
            elif method =="ASC":
                st = "SELECT r.restaurant_id, r.name, AVG(w.unlisted_at - w.listed_at) AS avg_waiting, COUNT (w.customer_id) As avg_customer FROM restaurant r LEFT JOIN waitlist w ON r.restaurant_id = w.restaurant_id GROUP BY r.restaurant_id ORDER BY avg_waiting ASC"
            cur = db.engine.execute(st)
            rows = cur.fetchall();
        return render_template("restaurants/index.html", rows=rows)
    else:
        if request.values.has_key('restaurant_id') and len(request.values['restaurant_id']) > 0:
            cur = db.engine.execute("SELECT * FROM (SELECT r.restaurant_id, r.name, AVG(w.unlisted_at - w.listed_at) AS avg_waiting, COUNT (w.customer_id) As avg_customer  FROM restaurant r LEFT JOIN waitlist w ON r.restaurant_id = w.restaurant_id GROUP BY r.restaurant_id ORDER BY avg_waiting) AS r WHERE r.restaurant_id = %s", request.values['restaurant_id'])
            rows = cur.fetchall();
            return render_template("restaurants/index.html", rows=rows)
        else:
            cur = db.engine.execute("SELECT r.restaurant_id, r.name, AVG(w.unlisted_at - w.listed_at) AS avg_waiting, COUNT (w.customer_id) As avg_customer FROM restaurant r LEFT JOIN waitlist w ON r.restaurant_id = w.restaurant_id GROUP BY r.restaurant_id ORDER BY avg_waiting")
            rows = cur.fetchall();
            return render_template("restaurants/index.html", rows=rows)
@mod_restaurant.route('/new')
@login_required
def new():
    return render_template('restaurants/new.html')

@mod_restaurant.route('/edit', methods=['GET'])
@login_required
def edit():
    id = request.values['id']
    cur = db.engine.execute("SELECT * FROM restaurant WHERE restaurant_id = %s LIMIT 1", id)
    restaurant = cur.fetchone()
    return render_template("restaurants/edit.html", restaurant=restaurant)

@mod_restaurant.route('/create', methods=['POST'])
@login_required
def create():
    if request.method == 'POST':
        msg = "Record successfully added"
        connection = db.engine.connect()
        trans = connection.begin()
        try:
            idn = request.form['id']
            nm = request.form['name']
            connection.execute("INSERT INTO restaurant VALUES (%s, %s)", (idn,nm))
            trans.commit()
            msg = "Record successfully added"
        except:
            trans.rollback()
            msg = "error in insert operation"
        finally:
            connection.close()
            return render_template("result.html", msg=msg, url = url_for('restaurants.main'))

@mod_restaurant.route('/delete', methods=['POST'])
@login_required
def delete():
    if request.method == 'POST':
        msg = "Record successfully Deleted"
        connection = db.engine.connect()
        trans = connection.begin()
        try:
            restaurant_id= request.form['restaurant_id']
            connection.execute("DELETE  from restaurant where restaurant_id= %s ", (restaurant_id,))
            trans.commit()
            msg = "Record successfully Deleted"
        except:
            trans.rollback()
            msg = "error in delete operation"
        finally:
            connection.close()
            return render_template("result.html", msg=msg, url = url_for('restaurants.main'))

@mod_restaurant.route('/update', methods=['POST'])
@login_required
def update():
    if request.method == 'POST':
        msg = "Record successfully updated"
        connection = db.engine.connect()
        trans = connection.begin()
        try:
            restaurant_id = request.form['update_id']
            name= request.form['name']
            old_id = request.form['old_id']
            connection.execute("UPDATE restaurant SET restaurant_id = %s, name = %s WHERE restaurant_id = %s", (restaurant_id, name, old_id))
            trans.commit()
            msg = "Record successfully updated"
        except:
            trans.rollback()
            msg = "error in update operation"
        finally:
            connection.close()
            return render_template("result.html", msg=msg, url = url_for('restaurants.main'))

app/views/table.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for
from app.decorators import login_required
from app import db
import pdb

mod_table = Blueprint('tables', __name__, url_prefix='/tables', template_folder='templates' )

@mod_table.route('/index')
@login_required
def index():
    if request.values.has_key('restaurant_id') and len(request.values['restaurant_id']) > 0:
        restaurant_id= request.values['restaurant_id']
        cur = db.engine.execute("with s(restaurant_id, name, table_id, seats) as (select restaurant.restaurant_id, restaurant.name, restaurant_table.table_id , restaurant_table.seats from restaurant_table, restaurant where restaurant_table.restaurant_id = restaurant.restaurant_id) select * from s where restaurant_id =%s ", restaurant_id)
        rows = cur.fetchall();
        return render_template("tables/index.html", rows=rows)
    else:
        cur = db.engine.execute("select restaurant.restaurant_id, restaurant.name, restaurant_table.table_id , restaurant_table.seats from restaurant_table, restaurant where restaurant_table.restaurant_id = restaurant.restaurant_id")
        rows = cur.fetchall();
        return render_template("tables/index.html", rows=rows)

@mod_table.route('/search', methods=['GET', 'POST'])
@login_required
def search():
    if request.method == "POST":
        if request.values.has_key('seats') and len(request.values['seats']) > 0:
            seats= request.form['seats']
            print seats
            condition= request.form.get('condition')
            print condition
            if condition =="equal to":
                cur = db.engine.execute("select r.restaurant_id, r.name, rt.table_id, rt.seats from restaurant_table rt, restaurant r where rt.restaurant_id = r.restaurant_id and rt.seats = %s ", [seats])
                rows= cur.fetchall();
            elif condition =="at least":
                cur = db.engine.execute("select r.restaurant_id, r.name, rt.table_id, rt.seats from restaurant_table rt, restaurant r where rt.restaurant_id = r.restaurant_id and rt.seats >= %s ", [seats])
                rows= cur.fetchall();
            elif condition =="at most":
                cur = db.engine.execute("select r.restaurant_id, r.name, rt.table_id, rt.seats from restaurant_table rt, restaurant r where rt.restaurant_id = r.restaurant_id and rt.seats <= %s ", [seats])
                rows= cur.fetchall();
            else:
                cur = db.engine.execute("select r.restaurant_id, r.name, rt.table_id, rt.seats from restaurant_table rt, restaurant r where rt.restaurant_id = r.restaurant_id and rt.seats ")
                rows= cur.fetchall();
            return render_template('tables/search.html', rows1 = rows)
        else:
            cur = db.engine.execute("select r.restaurant_id, r.name, rt.table_id, rt.seats from restaurant_table rt, restaurant r where rt.restaurant_id = r.restaurant_id")
            rows= cur.fetchall();
            return render_template('tables/search.html', rows1 = rows)
    return render_template('tables/search.html', rows1 = [])

@mod_table.route('/new')
@login_required
def new():
    return render_template('tables/new.html')

@mod_table.route('/edit', methods=['GET'])
@login_required
def edit():
    table_id = request.values['table_id']
    restaurant_id = request.values['restaurant_id']
    cur = db.engine.execute("select * from restaurant_table WHERE table_id=%s AND restaurant_id=%s LIMIT 1", (table_id, restaurant_id))
    table = cur.fetchone()
    return render_template('tables/edit.html', table=table)

@mod_table.route('/create', methods=['POST'])
@login_required
def create():
    if request.method == 'POST':
        msg = "Record successfully added"
        connection = db.engine.connect()
        trans = connection.begin()
        try:
            table_id= request.form['table_id']
            seats= request.form['seats']
            restaurant_id = request.form['restarant_id']
            connection.execute("INSERT INTO restaurant_table VALUES (%s, %s, %s)", (table_id, seats, restaurant_id))
            trans.commit()
            msg = "Record successfully added"
        except:
            trans.rollback()
            msg = "error in insert operation"
        finally:
            connnection.close()
            return render_template("result.html", msg=msg, url = url_for('restaurants.main') )

@mod_table.route('/update', methods=['POST'])
@login_required
def update():
    if request.method == 'POST':
        msg = "Record successfully added"
        connection = db.engine.connect()
        trans = connection.begin()
        try:
            table_id = request.form['update_id']
            seats= request.form['seats']
            restaurant_id = request.form['restaurant_id']
            old_id = request.form['old_id']
            old_restaurant_id = request.form['old_restaurant_id']
            connection.execute("UPDATE restaurant_table SET table_id = %s, seats = %s, restaurant_id = %s WHERE table_id = %s AND restaurant_id = %s", (table_id, seats, restaurant_id, old_id, old_restaurant_id))
            trans.commit()
            msg = "Record successfully updated"
        except:
            trans.rollback()
            msg = "error in update operation"
        finally:
            connection.close()
            return render_template("result.html", msg=msg, url = url_for('restaurants.main') )

@mod_table.route('/delete', methods=['POST'])
@login_required
def delete():
    if request.method == 'POST':
        msg = "Record successfully Deleted"
        connection = db.engine.connect()
        trans = connection.begin()
        try:
            id_table= request.form['table_id']
            print id_table
            connection.execute("DELETE  from restaurant_table where table_id= %s ", (id_table,))
            trans.commit()
            msg = "Record successfully Deleted"
        except:
            trans.rollback()
            msg = "error in delete operation"
        finally:
            connection.close()
            return render_template("result.html", msg=msg, url = url_for('restaurants.main') )

app/templates/restaurants/edit.html
{% extends "layouts/base.html" %}
{% block content %}
<form action = "{{ url_for('restaurants.update') }}" method ="POST">
  <h3>Enter Restaurant Information</h3>
  <input type = hidden name = "old_id" value = "{{ restaurant[0] }}" />
  Restaurant_ID<br>
  <input type = "INT" name = "update_id" value = "{{ restaurant[0] }}" /><br>
  Resturant_name<br>
  <input type = "text" name = "name" value = "{{ restaurant[1] }}" /></br>
  <input type = "submit" value = "submit" /><br>
</form>
{% endblock %}

app/templates/restaurants/index.html
{% extends "layouts/base.html" %}
{% block content %}
<h2 align="center"> Restaurant Information </h2>
<form  method = "GET">
  <h3>Filter by Restauarant_Id</h3>
  <input type = "INT" name = "restaurant_id" />
  <input type = "submit" value = "submit" /><br>
</form>


<h3 > Sort Restaurant Information </h3>
<form action = "{{ url_for('restaurants.index') }}" method = "POST">
  <select name="sort_type">
    <option value="customer number"> customer number </option>
    <option value="waiting time"> waiting time </option>
  </select> 
  <select name="method">
    <option value="DESC"> DESC </option>
    <option value="ASC">  ASC </option>
  </select> 

  <input type = "submit" value = "Sort" /><br>

  
</form>


<br>



<div class="table-responsive-vertical shadow-z-1">
  <!-- Table starts here -->
  <table id="table" class="table table-hover table-mc-light-blue">
    <thead>
      <tr>
        <th><b>Restaurant ID</b></th>
        <th><b>Restaurant Name</b></th>
        <th> <b>Average Waiting Time </b> </th>
        <th> <b>Average Visiting Customers</b> </th>


      </tr>
    </thead>
    <tbody>
      {% for row in rows %}
      <tr>
        <td>{{row[0]}}</td>
        <td>{{row[1]}}</td>
        <td>{{row[2]}}</td>
        <td>{{row[3]}}</td>
        <td>
          <form action="{{ url_for('restaurants.delete') }}" method=post class=deleterestaurant>
            <input type = hidden name = "restaurant_id" value = "{{row[0]}}"/>
            <input type=submit value = Delete></input>
          </form>
        </td>
        <td>
          <form action="{{ url_for('restaurants.edit') }}" method=get >
            <input type = hidden name = "id" value = "{{row[0]}}"/>
            <input type=submit value = Edit></input>
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

app/templates/restaurants/main.html
{% extends "layouts/base.html" %}
{% block content %}
<!-- Page Features -->
<div class="row text-center">
  <div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
      <div class="caption">
        <h3>Add new restaurant</h3>
        <p>
        <a href={{ url_for('restaurants.new') }} class="btn btn-primary">Add new</a> 
        </p>
      </div>
    </div>
  </div>
  <div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
      <div class="caption">
        <h3>Restaurants List</h3>
        <p>
        <a href={{ url_for('restaurants.index') }} class="btn btn-primary">Display</a> 
        </p>
      </div>
    </div>
  </div>
</div>
<!-- /.row -->
<!-- Page Features -->
<div class="row text-center">
  <div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
      <img src="" alt="" height="400" width="420">
      <div class="caption">
        <h3>Add new tables </h3>
        <p>
        <a href={{ url_for('tables.new') }} class="btn btn-primary">Add new</a> 
        </p>
      </div>
    </div>
  </div>
  <div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
      <img src="" alt="" height="400" width="420">
      <div class="caption">
        <h3>Show Restaurant Table Information</h3>
        <p>
        <a href={{ url_for('tables.index') }} class="btn btn-primary">Display</a> 
        </p>
      </div>
    </div>
  </div>
  <div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
      <img src="" alt="" height="400" width="420">
      <div class="caption">
        <h3>Search Restaurant Table With Size</h3>
        <p>
        <a href={{ url_for('tables.search') }} class="btn btn-primary"> Search</a> 
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/restaurants/new.html
{% extends "layouts/base.html" %}
{% block content %}
<form action = "{{ url_for('restaurants.create') }}" method = "POST">
  <h3>Restaurant Information</h3>
  Restaurant_ID<br>
  <input type = "INT" name = "id" /></br>
  Restaurant_Name<br>
  <input type = "text" name = "name" /><br>
  <input type = "submit" value = "submit" /><br>
</form>
{% endblock %}