app/views/customer.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for
from app.decorators import login_required
from app import db
import pdb

mod_customer = Blueprint('customers', __name__, url_prefix='/customers', template_folder='templates' )

@mod_customer.route('/main')
@login_required
def main():
    return render_template('customer/main.html')

@mod_customer.route('/')
@login_required
def index():
    if request.values.has_key('customer_id') and len(request.values['customer_id']) > 0:
        cur = db.engine.execute("select * from (SELECT * FROM customer ORDER BY customer_id) c where c.customer_id =%s", request.values['customer_id'])
        rows = cur.fetchall();
        return render_template("customer/index.html", rows=rows)
    else:
        cur = db.engine.execute("SELECT * FROM customer ORDER BY customer_id")
        rows = cur.fetchall();
        return render_template("customer/index.html", rows=rows)

@mod_customer.route('/new', methods=['GET'])
@login_required
def new():
    return render_template('customer/new.html', url="customer")

@mod_customer.route('/edit', methods=['GET'])
@login_required
def edit():
    id = request.values['id']
    cur = db.engine.execute("SELECT * FROM customer WHERE customer_id = %s LIMIT 1", id)
    customer = cur.fetchone()
    return render_template("customer/edit.html", customer=customer)

@mod_customer.route('/create', methods=['POST'])
@login_required
def create():
    if request.method == 'POST':
        msg = "Record successfully added"
        connection = db.engine.connect()
        trans = connection.begin()
        try:
            idn= request.form['id']
            first_nm = request.form['first_nm']
            last_nm= request.form['last_nm']
            phone = request.form['phone']
            email = request.form['email']
            connection.execute("INSERT INTO customer VALUES (%s, %s, %s, %s, %s)", (idn,first_nm, last_nm, phone, email))
            trans.commit()
            msg = "Record successfully added"
        except:
            trans.rollback()
            msg = "error in insert operation"
        finally:
            connection.close()
            return render_template("result.html", msg=msg, url=url_for('customers.main'))

@mod_customer.route('/delete', methods=['POST'])
@login_required
def delete():
    if request.method == 'POST':
        msg = "Record successfully Deleted"
        connection = db.engine.connect()
        trans = connection.begin()
        try:
            id_admin= request.form['id']
            print id_admin
            connection.execute("DELETE from customer where customer_id= %s", id_admin)
            trans.commit()
            msg = "Record successfully Deleted"
        except:
            trans.rollback()
            msg = "error in delete operation"
        finally:
            connection.close()
            return render_template("result.html", msg=msg, url = url_for('customers.main'))

@mod_customer.route('/update', methods=['POST'])
@login_required
def update():
    if request.method == 'POST':
        msg = "Record successfully added"
        connection = db.engine.connect()
        trans = connection.begin()
        try:
            customer_id = request.form['update_id']
            first_name= request.form['first_nm']
            last_name = request.form['last_nm']
            phone= request.form['phone']
            email = request.form['email']
            old_id = request.form['old_id']
            connection.execute("UPDATE customer SET customer_id = %s, first_name = %s, last_name = %s, phone_number = %s, customer_email = %s WHERE customer_id = %s", (customer_id, first_name, last_name, phone, email, old_id))
            trans.commit()
            msg = "Record successfully updated"
        except:
            trans.rollback()
            msg = "error in update operation"
        finally:
            connection.close()
            return render_template("result.html", msg=msg, url = url_for('customers.main'))

@mod_customer.route('/search', methods=['GET', 'POST'])
@login_required
def search():
    if request.method == "POST":
        customer_id= request.form['customer_id']
        cur = db.engine.execute("select * from customer where customer_id= %s", [customer_id])
        rows= cur.fetchall();
        return render_template('customer/search.html', rows1 = rows)
    return render_template('customer/search.html', rows1 = [])

@mod_customer.route('/dinning')
@login_required
def dinning():
    if request.values.has_key('customer_id') and len(request.values['customer_id']) > 0:
        cur = db.engine.execute("with t (customer_id, first_name, last_name, restaurant_id, name, count) as (SELECT c.customer_id, c.first_name, c.last_name, r.restaurant_id, r.name, t.count FROM  (SELECT p.customer_id, p.restaurant_id, COUNT(p.party_datetime) FROM party p, restaurant r WHERE p.restaurant_id = r.restaurant_id GROUP BY p.customer_id, p.restaurant_id ORDER BY customer_id, restaurant_id) t, customer c,restaurant r WHERE t.customer_id = c.customer_id AND r.restaurant_id = t.restaurant_id) select * from t where customer_id = %s", request.values["customer_id"])
        rows = cur.fetchall();
        return render_template('customer/dinning.html', rows= rows)
    else:
        cur = db.engine.execute("SELECT c.customer_id, c.first_name, c.last_name, r.restaurant_id, r.name, t.count FROM (SELECT p.customer_id, p.restaurant_id, COUNT(p.party_datetime) FROM party p, restaurant r WHERE p.restaurant_id = r.restaurant_id GROUP BY p.customer_id, p.restaurant_id ORDER BY customer_id, restaurant_id) t, customer c,restaurant r WHERE t.customer_id = c.customer_id AND r.restaurant_id = t.restaurant_id")
        rows = cur.fetchall();
        return render_template('customer/dinning.html', rows= rows)

app/templates/customer/dinning.html
{% extends "layouts/base.html" %}
{% block content %}
<h2 align="center"> Customer Dinning Information </h2>

<form  method = "GET">
  <h3>Filter by Customer Id</h3>
  <input type = "INT" name = "customer_id" />
  <input type = "submit" value = "submit" /><br>
</form>

<br>

<div class="table-responsive-vertical shadow-z-1">
  <!-- Table starts here -->
  <table id="table" class="table table-hover table-mc-light-blue">
    <thead>
      <tr>
        <th>Customer ID</th>
         <th>First name</th>
         <th> Last name </th>
         <th> Restaurant ID </th>
         <th> Restaurant Name </th>
         <th>Dinning Times</th>
      </tr>
    </thead>
    <tbody>
      {% for row in rows %}
      <tr>
        <td>{{row[0]}}</td>
        <td>{{row[1]}}</td>
         <td>{{row[2]}}</td>
        <td>{{row[3]}}</td>
        <td>{{row[4]}}</td>
         <td>{{row[5]}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

app/templates/customer/edit.html
{% extends "layouts/base.html" %}
{% block content %}
<form action = "{{ url_for('customers.update') }}" method = "POST">
  <h3>Enter Customer Information</h3>
  <input type = hidden name = "old_id" value = "{{ customer[0] }}" />
  Customer_ID<br>
  <input type = "INT" name = "update_id" value = "{{ customer[0] }}" /><br>
  First_Name<br>
  <input type = "text" name = "first_nm" value = "{{ customer[1] }}" /></br>
  Last_Name<br>
  <input type = "text" name = "last_nm" value = "{{ customer[2] }}" /></br>
  Phone_number<br>
  <input type = "text" name = "phone" value = "{{ customer[3] }}" /><br>
  Customer_email<br>
  <input type = "text" name = "email" value = "{{ customer[4] }}" /><br>
  <input type = "submit" value = "Update" /><br>
</form>
{% endblock %}

app/templates/customer/index.html
{% extends "layouts/base.html" %}
{% block content %}
<h2 align="center"> Customer Information </h2>
<form  method = "GET">
  <h3>Filter by Customer Id</h3>
  <input type = "INT" name = "customer_id" />
  <input type = "submit" value = "submit" /><br>
</form>

<br>

<div class="table-responsive-vertical shadow-z-1">
  <!-- Table starts here -->
  <table id="table" class="table table-hover table-mc-light-blue">
    <thead>
      <tr>
        <th><b>Customer_ID </b></th>
        <th> <b>First_Name </b></th>
        <th> <b>Last_name</b></th>
        <th><b>Phone_number</b></th>
        <th><b>cusotmer_email</b></th>
      </tr>
    </thead>
    <tbody>
      {% for row in rows %}
      <tr>
        <td>{{row[0]}}</td>
        <td>{{row[1]}}</td>
        <td> {{row[2]}}</td>
        <td>{{row[3]}}</td>
        <td>{{row[4]}}</td>
        <td>
          <form action="{{ url_for('customers.delete') }}" method=post class=deletecustomer>
            <input type = hidden name = "id" value = "{{row[0]}}"/>
            <input type=submit value = Delete></input>
          </form>
        </td>
        <td>
          <form action="{{ url_for('customers.edit') }}" method=get>
            <input type = hidden name = "id" value = "{{row[0]}}"/>
            <input type=submit value = Edit></input>
          </form>
        </td>
        <td>{{msg}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

app/templates/customer/main.html
{% extends "layouts/base.html" %}
{% block content %}
<!-- Page Features -->
<div class="row text-center">
  <div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
      <div class="caption">
        <h3>Add new customers</h3>
        <p>
        <a href={{ url_for('customers.new') }} class="btn btn-primary">Add new</a> 
        </p>
      </div>
    </div>
  </div>
  <div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
      <div class="caption">
        <h3>Show Full Customer List</h3>
        <p>
        <a href={{ url_for('customers.index') }} class="btn btn-primary">Display</a> 
        </p>

      </div>
    </div>
  </div>
  <div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
      <div class="caption">
        <h3>Search Customer Basic Information</h3>
        <p>
        <a href={{ url_for('customers.search') }} class="btn btn-primary">Search</a> 
        </p>
      </div>
    </div>
  </div>
  <div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
      <div class="caption">
        <h3>Search Customer Dining Information</h3>
        <p>
        <a href={{ url_for('customers.dinning') }} class="btn btn-primary">Search</a>
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/customer/new.html
{% extends "layouts/base.html" %}
{% block content %}
<form action = "{{ url_for('customers.create') }}" method = "POST">
  <h3>Enter Customer Information</h3>
  Customer_ID<br>
  <input type = "INT" name = "id" /><br>
  First_Name<br>
  <input type = "text" name = "first_nm" /></br>
  Last_Name<br>
  <input type = "text" name = "last_nm" /></br>
  Phone_number<br>
  <input type = "text" name = "phone" /><br>
  Customer_email<br>
  <input type = "text" name = "email" /><br>
  <input type = "submit" value = "submit" /><br>
</form>

{% endblock %}

app/templates/customer/search.html
{% extends "layouts/base.html" %}
{% block content %}
<form action = "{{ url_for('customers.search') }}" method = "POST">
  <h3>Enter Customer Information</h3>
  customer_id<br>
  <input type = "INT" name = "customer_id" /></br>    
  <input type = "submit" value = "submit" /><br>
</form>
<table border = 1>
  <thead>
    <td>customer_id</td>
    <td>First_name</td>
    <td>Last_name</td>
    <td>Phone_number</td>
    <td>customer_email</td>
  </thead>
  {% for row in rows1 %}
  <tr>
    <td>{{row[0]}}</td>
    <td>{{row[1]}}</td>
    <td> {{row[2]}}</td>
    <td>{{row[3]}}</td>
    <td>{{row[4]}}</td>
  </tr>
  {% endfor %}
</table>
{% endblock %}