app/views/admin.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for
from app.decorators import login_required
from app import db
import pdb

mod_admin = Blueprint('admins', __name__, url_prefix='/admins', template_folder='templates' )

@mod_admin.route('/main')
@login_required
def main():
    return render_template('admins/main.html')

@mod_admin.route('/')
@login_required
def index():
    if request.values.has_key('admin_id') and len(request.values['admin_id']) > 0:
        cur = db.engine.execute("select * from administrator where admin_id = %s", request.values["admin_id"])
        rows = cur.fetchall();
        return render_template("admins/index.html", rows=rows)
    else:
        cur = db.engine.execute("select * from administrator ORDER BY admin_id")
        rows = cur.fetchall();
        return render_template("admins/index.html", rows=rows)

@mod_admin.route('/new')
@login_required
def new():
    return render_template('admins/new.html', url = 'admin')

@mod_admin.route('/edit', methods=['GET'])
@login_required
def edit():
    id = request.values['id']
    cur = db.engine.execute("select * from administrator WHERE admin_id = %s LIMIT 1", id)
    admin = cur.fetchone()
    return render_template("admins/edit.html", admin = admin)

@mod_admin.route('/create', methods=['POST'])
@login_required
def create():
    if request.method == 'POST':
        connection = db.engine.connect()
        trans = connection.begin()
        try:
            idn = request.form['id']
            email = request.form['email']
            nm = request.form['nm']
            pin= request.form['pin']
            connection.execute("INSERT INTO administrator VALUES (%s, %s, %s, %s)", (idn,email, nm, pin))
            trans.commit()
            msg = "Record successfully added"
        except:
            trans.rollback()
            msg = "error in insert operation"
        finally:
            connection.close()
            return render_template("result.html", msg=msg, url = url_for('admins.main') )

@mod_admin.route('/update', methods=['POST'])
@login_required
def update():
    if request.method == 'POST':
        msg = "Record successfully added"
        connection = db.engine.connect()
        trans = connection.begin()
        try:
            admin_id = request.form['update_id']
            user_name= request.form['user_name']
            password = request.form['password']
            email= request.form['email']
            old_id = request.form['old_id']
            connection.execute("UPDATE administrator SET admin_id = %s, user_name = %s, email =%s, encrypted_password= %s WHERE admin_id = %s", (admin_id, user_name, email, password, old_id))
            trans.commit()
            msg = "Record successfully updated"
        except:
            trans.rollback()
            msg = "error in update operation"
        finally:
            connection.close()
            return render_template("result.html", msg=msg, url = url_for('admins.main') )

@mod_admin.route('/delete', methods=['POST'])
@login_required
def delete():
    if request.method == 'POST':
        msg = "Record successfully Deleted"
        connection = db.engine.connect()
        trans = connection.begin()
        try:
            id_admin= request.form['id']
            print id_admin
            connection.execute("DELETE  from administrator where admin_id= %s ", (id_admin,))
            trans.commit()
            msg = "Record successfully Deleted"
        except:
            trans.rollback()
            msg = "error in delete operation"
        finally:
            connection.close()
            return render_template("result.html", msg=msg, url = url_for('admins.main') )

app/views/manage.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for
from app.decorators import login_required
from app import db
import pdb

mod_manage = Blueprint('manage', __name__, url_prefix='/manage', template_folder='templates' )

@mod_manage.route('/')
@login_required
def index():
    if request.values.has_key('admin_id') and len(request.values['admin_id']) > 0:
        admin_id = request.values['admin_id']
        print admin_id
        cur = db.engine.execute("with s (admin_id, email, restaurant_id, name) as (select m.admin_id, a.email, m.restaurant_id, r.name from manage m, administrator a, restaurant r WHERE m.admin_id = a.admin_id AND m.restaurant_id = r.restaurant_id) select * from s where admin_id = %s", (admin_id,))
        rows = cur.fetchall()
        return render_template('manage/index.html', rows=rows)

    elif request.values.has_key('restaurant_id') and len(request.values['restaurant_id']) > 0:
        restaurant_id = request.values['restaurant_id']
        cur = db.engine.execute("with s (admin_id, email, restaurant_id, name) as (select m.admin_id, a.email, m.restaurant_id, r.name from manage m, administrator a, restaurant r WHERE m.admin_id = a.admin_id AND m.restaurant_id = r.restaurant_id) select * from s where restaurant_id = %s", (restaurant_id,))
        rows = cur.fetchall()
        return render_template('manage/index.html', rows=rows)
    else:
        cur = db.engine.execute("select m.admin_id, a.email, m.restaurant_id, r.name from manage m, administrator a, restaurant r WHERE m.admin_id = a.admin_id AND m.restaurant_id = r.restaurant_id")
        rows = cur.fetchall()
        return render_template('manage/index.html', rows=rows)

@mod_manage.route('/new')
@login_required
def new():
    return render_template('manage/new.html', url = url_for("admins.main"))

@mod_manage.route('/edit', methods=['GET'])
@login_required
def edit():
    restaurant_id = request.values['restaurant_id']
    admin_id = request.values['admin_id']
    cur = db.engine.execute('select * from manage WHERE admin_id= %s AND restaurant_id= %s LIMIT 1', (admin_id, restaurant_id))
    manage = cur.fetchone()
    return render_template('manage/edit.html', manage=manage, url = url_for("admins.main"))

@mod_manage.route('/create', methods=['POST'])
@login_required
def create():
    if request.method == 'POST':
        connection = db.engine.connect()
        trans = connection.begin()
        try:
            admin_id = request.form['admin_id']
            restaurant_id = request.form['restaurant_id']
            connection.execute("INSERT INTO manage VALUES (%s, %s)", (restaurant_id, admin_id))
            trans.commit()
            msg = "Record successfully added"
        except:
            trans.rollback()
            msg = "error in insert operation"
        finally:
            connection.close()
            return render_template("result.html", msg=msg, url = url_for("admins.main"))

@mod_manage.route('/delete', methods=['POST'])
@login_required
def delete():
    if request.method == 'POST':
        connection = db.engine.connect()
        trans = connection.begin()
        try:
            admin_id = request.form['admin_id']
            restaurant_id = request.form['restaurant_id']
            connection.execute("DELETE FROM manage WHERE admin_id= %s AND restaurant_id= %s", (admin_id, restaurant_id))
            trans.commit()
            msg = "Record successfully removed"
        except:
            trans.rollback()
            msg = "error in insert operation"
        finally:
            connection.close()
            return render_template("result.html", msg=msg, url = url_for("admins.main"))

@mod_manage.route('/update', methods=['POST'])
@login_required
def update():
    if request.method == 'POST':
        msg = "Record successfully updated"
        connection = db.engine.connect()
        trans = connection.begin()
        try:
            admin_id = request.form['admin_id']
            restaurant_id = request.form['restaurant_id']
            old_restaurant_id = request.form['old_restaurant_id']
            old_admin_id = request.form['old_admin_id']
            db.engine.execute("UPDATE manage SET restaurant_id = %s, admin_id = %s WHERE restaurant_id = %s AND admin_id = %s", (restaurant_id, admin_id, old_restaurant_id, old_admin_id))
            msg = "Record successfully updated"
        except:
            trans.rollback()
            msg = "error in update operation"
        finally:
            connection.close()
            return render_template("result.html", msg=msg, url = url_for('admins.main'))

app/templates/admins/edit.html
{% extends "layouts/base.html" %}
{% block content %}
<form action = "{{ url_for('admins.update') }}" method = "POST">
  <h3>Enter Admin Information</h3>
  <input type = hidden name = "old_id" value = "{{ admin[0] }}" />
  Admin_ID<br>
  <input type = "INT" name = "update_id" value = "{{ admin[0] }}" /><br>
  email<br>
  <input type = "text" name = "email" value = "{{ admin[1] }}" /></br>
  User_name<br>
  <input type = "text" name = "user_name" value = "{{ admin[2] }}" /></br>
  Password<br>
  <input type = "password" name = "password" value = "{{ admin[3] }}" /></br>
  <input type = "submit" value = "submit" /><br>
</form>

{% endblock %}

app/templates/admins/index.html
{% extends "layouts/base.html" %}
{% block content %}
<h2 align="center"> Administrators Information </h2>

<form  method = "GET">
  <h3>Filter by Admin Id</h3>
  <input type = "INT" name = "admin_id" />
  <input type = "submit" value = "submit" /><br>
</form>

<br>


<div class="table-responsive-vertical shadow-z-1">
  <!-- Table starts here -->
  <table id="table" class="table table-hover table-mc-light-blue">
    <thead>
      <tr>
        <th><b>Admin_ID</b></th>
        <th><b>Email</b></th>
        <th><b>User_name</b></th>
        <th><b>Password</b></th>
      </tr>
    </thead>
    <tbody>
      {% for row in rows %}
      <tr>
        <td > {{row[0]}}</td>
        <td>{{row[1]}}</td>
        <td> {{row[2]}}</td>
        <td>{{row[3]}}</td>
        <td>
          <form action="{{ url_for('admins.delete') }}" method=post class=deleteadmin>
            <input type = hidden name = "id" value = "{{row[0]}}"/>
            <input type=submit value = Delete></input>
          </form>
        </td>
          <td>
          <form action="{{ url_for('admins.edit') }}" method=get>
            <input type = hidden name = "id" value = "{{row[0]}}"/>
            <input type=submit value = Edit></input>
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

app/templates/admins/main.html
{% extends "layouts/base.html" %}
{% block content %}
<!-- Page Features -->
<div class="row text-center">
  <div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
      <img src="" alt="" height="400" width="420">
      <div class="caption">
        <h3>Add administrator</h3>
        <p>
        <a href={{ url_for('admins.new') }} class="btn btn-primary">Add Administrator</a> 
        </p>
      </div>
    </div>
  </div>
  <div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
      <img src="" alt="" height="400" width="420">
      <div class="caption">
        <h3>Show Admin Information</h3>
        <p>
        <a href={{ url_for('admins.index') }} class="btn btn-primary">Display</a> 
        </p>
      </div>
    </div>
  </div>
</div>
<!-- /.row -->
<!-- Page Features -->
<div class="row text-center">
  <div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
      <div class="caption">
        <h3>Add Manage</h3>
        <p>
        <a href={{ url_for('manage.new') }} class="btn btn-primary">Add Administrator</a> 
        </p>
      </div>
    </div>
  </div>
  <div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
      <div class="caption">
        <h3>Management List</h3>
        <p>
        <a href={{ url_for('manage.index') }} class="btn btn-primary">Management list</a> 
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/admins/new.html
{% extends "layouts/base.html" %}
{% block content %}
<form action = "{{ url_for('admins.create') }}" method = "POST">
  <h3>Admin Information</h3>
  admin_id<br>
  <input type = "INT" name = "id" /><br>
  email<br>
  <input type = "text" name = "email" /></br>
  user_name<br>
  <input type = "text" name = "nm" /><br>
  Password<br>
  <input type = "password" name = "pin" /><br>
  <input type = "submit" value = "submit" /><br>
</form>
{% endblock %}