app/views/auth.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for
from app.decorators import login_required
from app import db
import pdb

auth_mod = Blueprint('auth', __name__, template_folder='templates' )

@auth_mod.route('/login', methods=['GET', 'POST'])
def login():
    error = None
    user_password = False
    if request.method == 'POST':
        cur = db.engine
        admins = cur.execute("select * from administrator WHERE user_name=%s AND encrypted_password=%s", (request.form['username'], request.form['password']))
        admin = admins.fetchone();
        if request.form['username'] == 'admin' and request.form['password'] == 'admin':
            user_password = True 
        if user_password or (admin is not None):
            session['logged_in'] = True
            #flash('You were logged in.')
            return redirect(url_for('index'))
        else:
            error = 'Invalid Credentials. Please try again.'
    return render_template('login.html', error=error)

@auth_mod.route('/logout')
@login_required
def logout():
    session.pop('logged_in', None)
    flash('You were logged out.')
    return redirect(url_for('welcome'))

app/views/notification.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for
from app.decorators import login_required
from app import db

mod_notification = Blueprint('notifications', __name__, url_prefix='/notifications', template_folder='templates' )

@mod_notification.route('/')
@login_required
def index():
    cur = db.engine.execute("select * from notification")
    rows = cur.fetchall();
    return render_template("notifications/index.html", rows=rows)

@mod_notification.route('/create', methods=['POST'])
@login_required
def create():
    if request.method == 'POST':
        connection = db.engine.connect()
        trans = connection.begin()
        try:
            body= request.form['body']
            ntype= request.form['type']
            sent_at= request.form['sent_at']
            restaurant_id= request.form['restaurant_id']
            customer_id= request.form['customer_id']
            connection.execute("INSERT INTO notification VALUES (%s, %s, %s, %s, %s)", (body, ntype, sent_at, restaurant_id, customer_id))
            trans.commit()
            msg = "Record successfully added"
        except:
            trans.rollback()
            msg = "error in insert operation"
        finally:
            connection.close()
            return render_template("result.html", msg=msg, url = "/")

@mod_notification.route('/edit', methods=['GET'])
@login_required
def edit():
    restaurant_id = request.values['restaurant_id']
    customer_id = request.values['customer_id']
    sent_at = request.values['sent_at']
    cur = db.engine.execute("select * from notification WHERE restaurant_id=%s AND customer_id=%s AND sent_at=%s LIMIT 1", (restaurant_id, customer_id, sent_at))
    notification = cur.fetchone()
    return render_template('notifications/edit.html', notification=notification, url='/')

@mod_notification.route('/new')
@login_required
def new():
    return render_template('notifications/new.html', url = '/')

@mod_notification.route('/delete', methods=['POST'])
@login_required
def delete():
    if request.method == 'POST':
        connection = db.engine.connect()
        trans = connection.begin()
        msg = "Record successfully Deleted"
        try:
            sent_at= request.form['sent_at']
            restaurant_id= request.form['restaurant_id']
            customer_id= request.form['customer_id']
            connection.execute("DELETE  from notification where sent_at=%s AND restaurant_id =%s and customer_id= %s", (sent_at, restaurant_id, customer_id))
            trans.commit()
            msg = "Record successfully Deleted"
        except:
            trans.rollback()
            msg = "error in delete operation"
        finally:
            connection.close()
            return render_template("result.html", msg=msg, url = "/")

@mod_notification.route('/update', methods=['POST'])
@login_required
def update():
    if request.method == 'POST':
        connection = db.engine.connect()
        trans = connection.begin()
        try:
            old_restaurant_id= request.form['old_restaurant_id']
            old_customer_id= request.form['old_customer_id']
            old_sent_at = request.form['old_sent_at']
            restaurant_id= request.form['restaurant_id']
            customer_id= request.form['customer_id']
            sent_at = request.form['sent_at']
            notif_type = request.form['type']
            body = request.form['body']
            connection.execute("UPDATE notification SET restaurant_id = %s, customer_id = %s, sent_at = %s, type = %s, body = %s WHERE restaurant_id = %s AND customer_id = %s AND sent_at = %s", (restaurant_id, customer_id, sent_at, notif_type, body, old_restaurant_id, old_customer_id, old_sent_at))
            trans.commit()
            msg = "Record successfully updated"
        except:
            trans.rollback()
            msg = "error in update operation"
        finally:
            connection.close()
            return render_template("result.html", msg=msg, url = "/")

app/views/party.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for
from app.decorators import login_required
from app.utils import get_value
from app import db
import pdb

mod_party = Blueprint('party', __name__, url_prefix='/party', template_folder='templates' )

@mod_party.route('/', methods = ['GET', 'POST'])
@login_required
def index():
    if request.method == "POST":
    	condition = request.form.get ("condition")
    	if condition =="ongoing":
    		cur = 	db.engine.execute("select * from party where seated_datetime is not null and finish_at is null")
    		rows = cur.fetchall()
    	if condition =="finished":
    		cur = 	db.engine.execute("select * from party where seated_datetime is not null and finish_at is not null")
    		rows = cur.fetchall()
        if condition=="unseated":
    		cur = 	db.engine.execute("select * from party where seated_datetime is null")
    		rows = cur.fetchall()
        return render_template("party/index.html", rows=rows)
    elif request.method == "GET" and request.values.has_key("restaurant_id"):
        if request.values.has_key('party'):
            cur = db.engine.execute("select * from party where restaurant_id = %s and seated_datetime is NULL and finish_at is NULL", request.values["restaurant_id"])
            rows = cur.fetchall();
            return render_template("party/index.html", rows=rows)
        else:
            cur = db.engine.execute("select * from party where restaurant_id = %s", request.values["restaurant_id"])
            rows = cur.fetchall();
            return render_template("party/index.html", rows=rows)
    else:
        cur = db.engine.execute("SELECT  * from party")
        rows = cur.fetchall()
        return render_template("party/index.html", rows=rows)


@mod_party.route('/new')
@login_required
def new():
    return render_template('party/new.html', url = '/')

@mod_party.route('/edit', methods=['GET'])
@login_required
def edit():
    customer_id = request.values['customer_id']
    party_datetime = request.values['party_datetime']
    cur = db.engine.execute("select * from party WHERE customer_id=%s AND party_datetime=%s LIMIT 1", (customer_id, party_datetime))
    party = cur.fetchone()
    return render_template('party/edit.html', party=party, url='/')

@mod_party.route('/create', methods=['POST'])
@login_required
def create():
    if request.method == 'POST':
        connection = db.engine.connect()
        trans = connection.begin()
        try:
            size = request.form['size']
            customer_id= request.form['customer_id']
            party_datetime= request.form['party_datetime']
            table_id= get_value(request,'table_id')
            restaurant_id= get_value(request,'restaurant_id')
            seated_datetime= get_value(request,'seated_datetime')
            finish_at= get_value(request, 'finish_at')
            db.engine.execute("INSERT INTO party VALUES (%s, %s, %s, %s, %s, %s, %s)", (size, customer_id, party_datetime, table_id, restaurant_id, seated_datetime, finish_at))
            trans.commit()
            msg = "Record successfully added"
        except:
            trans.rollback()
            msg = "error in insert operation"

        finally:
            connection.close()
            return render_template("result.html", msg=msg, url = "/")

@mod_party.route('/update', methods=['POST'])
@login_required
def update():
    if request.method == 'POST':
        connection = db.engine.connect()
        trans = connection.begin()
        try:
            old_customer_id= request.form['old_customer_id']
            old_party_datetime = request.form['old_party_datetime']
            size = request.form['size']
            customer_id= request.form['customer_id']
            party_datetime = request.form['party_datetime']
            table_id = get_value(request, 'table_id')
            restaurant_id = get_value(request, 'restaurant_id')
            seated_datetime = get_value(request, 'seated_datetime')
            finish_at = get_value(request, 'finish_at')
            connection.execute("UPDATE party SET size=%s, customer_id=%s,party_datetime=%s,table_id=%s,restaurant_id=%s,seated_datetime=%s, finish_at=%s  WHERE customer_id = %s AND  party_datetime = %s", (size, customer_id, party_datetime, table_id, restaurant_id, seated_datetime, finish_at, old_customer_id, old_party_datetime))
            trans.commit()
            msg = "Record successfully updated"
        except:
            trans.rollback()
            msg = "error in update operation"
        finally:
            connection.close()
            return render_template("result.html", msg=msg, url = "/")

@mod_party.route('/delete', methods=['POST'])
@login_required
def delete():
    if request.method == 'POST':
        msg = "Record successfully Deleted"
        connection = db.engine.connect()
        trans = connection.begin()
        try:
            customer_id= request.form['customer_id']
            party_datetime= request.form['party_time']
            connection.execute("DELETE  from party where customer_id= %s AND party_datetime= %s", (customer_id, party_datetime))
            trans.commit()
            msg = "Record successfully Deleted"
        except:
            trans.rollback()
            msg = "error in delete operation"
        finally:
            connection.close()
            return render_template("result.html", msg=msg, url = "/")

app/views/waitlist.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for
from app.decorators import login_required
from app.utils import get_value
from app import db
import pdb

mod_waitlist = Blueprint('waitlists', __name__, url_prefix='/waitlists', template_folder='templates')

@mod_waitlist.route('/')
@login_required
def index():
    if request.values.has_key('restaurant_id') and len(request.values['restaurant_id']) > 0:
        if request.values.has_key('waiting'):
            cur = db.engine.execute("select * from waitlist WHERE restaurant_id=%s AND unlisted_at IS NULL ORDER BY listed_at", request.values['restaurant_id'])
        else:
            cur = db.engine.execute("select * from waitlist WHERE restaurant_id=%s ORDER BY listed_at", request.values['restaurant_id'])
    else:
        if request.values.has_key('waiting'):
            cur = db.engine.execute("select * from waitlist WHERE unlisted_at IS NULL ORDER BY listed_at")
        else:
            cur = db.engine.execute("select * from waitlist ORDER BY listed_at")
    rows = cur.fetchall();
    return render_template("waitlist/index.html", rows=rows)

@mod_waitlist.route('/new')
@login_required
def new():
    return render_template('waitlist/new.html', url='index')

@mod_waitlist.route('/edit', methods=['GET'])
@login_required
def edit():
    restaurant_id = request.values['restaurant_id']
    customer_id = request.values['customer_id']
    party_datetime = request.values['party_datetime']
    cur = db.engine.execute("select * from waitlist WHERE restaurant_id=%s AND customer_id=%s AND party_datetime=%s LIMIT 1", (restaurant_id, customer_id, party_datetime))
    waitlist = cur.fetchone()
    return render_template('waitlist/edit.html', waitlist=waitlist, url='index')

@mod_waitlist.route('/create', methods=['POST'])
@login_required
def create():
    if request.method == 'POST':
        connection = db.engine.connect()
        trans = connection.begin()
        try:
            restaurant_id = request.form['restaurant_id']
            customer_id= request.form['customer_id']
            party_datetime= request.form['party_datetime']
            listed_at= request.form['listed_at']
            unlisted_at= get_value(request,'unlisted_at')
            db.engine.execute("INSERT INTO waitlist (restaurant_id, customer_id, party_datetime, listed_at, unlisted_at) VALUES (%s, %s, %s, %s, %s)", (restaurant_id, customer_id, party_datetime, listed_at, unlisted_at))
            trans.commit()
            msg = "Record successfully added"
        except:
            trans.rollback()
            msg = "error in insert operation"
        finally:
            connection.close()
            return render_template("result.html", msg=msg, url = "/")

@mod_waitlist.route('/update', methods=['POST', 'GET'])
@login_required
def update():
    if request.method == 'POST':
        connection = db.engine.connect()
        trans = connection.begin()
        try:
            old_restaurant_id = request.form['old_restaurant_id']
            old_customer_id = request.form['old_customer_id']
            old_party_datetime = request.form['old_party_datetime']
            restaurant_id= request.form['restaurant_id']
            customer_id= request.form['customer_id']
            party_datetime = request.form['party_datetime']
            listed_at = request.form['listed_at']
            unlisted_at = get_value(request, 'unlisted_at')
            connection.execute("UPDATE waitlist SET restaurant_id = %s, customer_id = %s, party_datetime = %s, listed_at = %s, unlisted_at = %s WHERE restaurant_id = %s AND customer_id = %s AND party_datetime = %s", (restaurant_id, customer_id, party_datetime, listed_at, unlisted_at, old_restaurant_id, old_customer_id, old_party_datetime))
            trans.commit()
            msg = "Record successfully updated"
        except:
            trans.rollback()
            msg = "error in update operation"
        finally:
            connection.close()
            return render_template("result.html", msg=msg, url = "/")

@mod_waitlist.route('/delete', methods=['POST', 'GET'])
@login_required
def delete():
    if request.method == 'POST':
        msg = "Record successfully Deleted"
        connection = db.engine.connect()
        trans = connection.begin()
        try:
            restaurant_id= request.form['restaurant_id']
            customer_id = request.form['customer_id']
            party_datetime = request.form['party_datetime']
            connection.execute("DELETE  from waitlist where restaurant_id= %s and customer_id = %s and party_datetime = %s ", (restaurant_id, customer_id, party_datetime))
            trans.commit()
            msg = "Record successfully Deleted"
        except:
            trans.rollback()
            msg = "error in delete operation"
        finally:
            connection.close()
            return render_template("result.html", msg=msg, url = "/")

app/templates/admin.html
{% extends "mainlayout.html" %}
{% block content %}
<!-- Page Features -->
<div class="row text-center">
  <div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
      <img src="" alt="" height="400" width="420">
      <div class="caption">
        <h3>Add more administrators</h3>
        <p>
        <a href="enteradmin" class="btn btn-primary">Add Administrator</a> 
        </p>
      </div>
    </div>
  </div>


  <div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
      <img src="" alt="" height="400" width="420">
      <div class="caption">
        <h3>Show Admin Information</h3>
        <p>
        <a href="adminlist" class="btn btn-primary">Display</a> 
        </p>
      </div>
    </div>
  </div>




</div>
<!-- /.row -->

<!-- Page Features -->
<div class="row text-center">

  <div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
      <img src="" alt="" height="400" width="420">
      <div class="caption">
        <h3>Add Manage</h3>

        <p>
        <a href="entermanage" class="btn btn-primary">Add Administrator</a> 
        </p>

      </div>
    </div>
  </div>

</div>
{% endblock %}

app/templates/adminlist.html
{% extends "mainlayout.html" %}
{% block content %}
<h2 align="center"> Administrators Information </h2>
<div class="table-responsive-vertical shadow-z-1">
  <!-- Table starts here -->
  <table id="table" class="table table-hover table-mc-light-blue">
    <thead>
      <tr>
        <th><b>Admin_ID</b></th>
        <th><b>Email</b></th>
        <th><b>User_name</b></th>
        <th><b>Password</b></th>

      </tr>
    </thead>
    <tbody>

      {% for row in rows %}
      <tr>
        <td > {{row[0]}}</td>
        <td>{{row[1]}}</td>
        <td> {{row[2]}}</td>
        <td>{{row[3]}}</td>
        <td>

          <form action="{{ url_for('deleteadmin') }}" method=post class=deleteadmin>
            <input type = hidden name = "id" value = "{{row[0]}}"/>
            <input type=submit value = Delete></input>
          </form>


        </td>

          <td>

          <form action="{{ url_for('updateadmin') }}" method=post class=updateadmin>
            <input type = hidden name = "old_id" value = "{{row[0]}}"/>
            <input type=submit value = Update></input>
          </form>


        </td>

      </tr>
      {% endfor %}

    </tbody>
  </table>
</div>  
{% endblock %}

app/templates/customer.html
{% extends "mainlayout.html" %}
{% block content %}
<!-- Page Features -->
<div class="row text-center">

  <div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
      <img src="" alt="" height="400" width="420">
      <div class="caption">
        <h3>Add new customers</h3>

        <p>
        <a href="entercustomer" class="btn btn-primary">Add new</a> 
        </p>
      </div>
    </div>
  </div>

  <div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
      <img src="" alt="" height="400" width="420">
      <div class="caption">
        <h3>Show Full Customer List</h3>
        <p>
        <a href="customerlist" class="btn btn-primary">Display</a> 
        </p>

      </div>
    </div>
  </div>

  <div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
      <img src="" alt="" height="400" width="420">
      <div class="caption">
        <h3>Search Customer Basic Information</h3>
        <p>
        <a href="search" class="btn btn-primary">Search</a> 
        </p>
      </div>
    </div>
  </div>

  <div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
      <img src="" alt="" height="400" width="420">
      <div class="caption">
        <h3>Search Customer Dining Information</h3>
        <p>
        <a href="dinning" class="btn btn-primary">Search</a> 
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/customerlist.html
{% extends "mainlayout.html" %}
{% block content %}
<h2 align="center"> Customer Information </h2>
<div class="table-responsive-vertical shadow-z-1">
  <!-- Table starts here -->
  <table id="table" class="table table-hover table-mc-light-blue">
    <thead>
      <tr>
        <th><b>Customer_ID </b></th>
        <th> <b>First_Name </b></th>
        <th> <b>Last_name</b></th>
        <th><b>Phone_number</b></th>
        <th><b>cusotmer_email</b></th>
      </tr>
    </thead>
    <tbody>

      {% for row in rows %}
      <tr>
        <td>{{row[0]}}</td>
        <td>{{row[1]}}</td>
        <td> {{row[2]}}</td>
        <td>{{row[3]}}</td>
        <td>{{row[4]}}</td>

        <td>

          <form action="{{ url_for('deletecustomer') }}" method=post class=deletecustomer>
            <input type = hidden name = "id" value = "{{row[0]}}"/>
            <input type=submit value = Delete></input>
          </form>
          </td>

          <td>
          <form action="{{ url_for('updatecustomer') }}" method=post class=updatecustomer>
             <input type = hidden name = "old_id" value = "{{row[0]}}"/>
            <input type=submit value = Update></input>
          </form>


        </td>

        <td>{{msg}}</td>


      </tr>
      {% endfor %}

    </tbody>
  </table>
</div>
{% endblock %}

app/templates/entercustomer.html
{% extends "mainlayout.html" %}
{% block content %}
<form action = "{{ url_for('addreccustomer') }}" method = "POST">
  <h3>Enter Customer Information</h3>

  Customer_ID<br>
  <input type = "INT" name = "id" /><br>

  First_Name<br>
  <input type = "text" name = "first_nm" /></br>

  Last_Name<br>
  <input type = "text" name = "last_nm" /></br>


  Phone_number<br>
  <input type = "text" name = "phone" /><br>

  Customer_email<br>
  <input type = "text" name = "email" /><br>
  <input type = "submit" value = "submit" /><br>
</form>

{% endblock %}

app/templates/enterrestaurant.html
{% extends "mainlayout.html" %}
{% block content %}
<form action = "{{ url_for('addrecrestaurant') }}" method = "POST">
  <h3>Restaurant Information</h3>
  Restaurant_ID<br>
  <input type = "INT" name = "id" /></br>

  Restaurant_Name<br>
  <input type = "text" name = "nm" /><br>



  <input type = "submit" value = "submit" /><br>
</form>
{% endblock %}

app/templates/entertable.html
{% extends "mainlayout.html" %}
{% block content %}
<form action = "{{ url_for('addrectable') }}" method = "POST">
  <h3>Table Information</h3>
  Table_ID<br>
  <input type = "INT" name = "table_id" /></br>

  Seats<br>
  <input type = "INT" name = "seats" /></br>

  Restaurant_ID <br>
  <input type = "INT" name = "restarant_id" /></br>

  <input type = "submit" value = "submit" /><br>
</form>
{% endblock %}

app/templates/index.html
{% extends "layouts/base.html" %}
{% block content %}
<!-- Jumbotron Header -->
<header class="jumbotron hero-spacer">
  <h1 >Welcome to <em>restaurant waiting list</em>!</h1>
  <hr>


  <!-- Page Features -->
  <div class="row text-center", align='center'>

    <div class="col-md-3 col-sm-6 hero-feature">
      <div class="thumbnail">
        <img src="" alt="" height="400" width="420">
        <div class="caption">
          <h3>Add New Party</h3>

          <p>
          <a href={{ url_for('party.new') }} class="btn btn-primary">Add Party</a> 
          </p>

        </div>
      </div>
    </div>


    <div class="col-md-3 col-sm-6 hero-feature">
      <div class="thumbnail">
        <img src="" alt="" height="400" width="420">
        <div class="caption">
          <h3>Show Party</h3>
          <p>
          <a href={{ url_for('party.index') }} class="btn btn-primary">Display</a> 
          </p>
        </div>
      </div>
    </div>

  </div>
  <!-- /.row -->

  <!-- Page Features -->
  <div class="row text-center">

    <div class="col-md-3 col-sm-6 hero-feature">
      <div class="thumbnail">
        <img src="" alt="" height="400" width="420">
        <div class="caption">
          <h3>New Notification</h3>
          <p>
          <a href={{ url_for('notifications.new') }} class="btn btn-primary">Add Notification</a> 
          </p>
        </div>
      </div>
    </div>

    <div class="col-md-3 col-sm-6 hero-feature">
      <div class="thumbnail">
        <img src="" alt="" height="400" width="420">
        <div class="caption">
          <h3>Show Notification Information</h3>
          <p>
          <a href="notifications" class="btn btn-primary">Display</a> 
          </p>
        </div>
      </div>
    </div>

  </div>
  <!-- /.row -->

  <!-- Page Features -->
  <div class="row text-center">

    <div class="col-md-3 col-sm-6 hero-feature">
      <div class="thumbnail">
        <img src="" alt="" height="400" width="420">
        <div class="caption">
          <h3>Add New Waitlist</h3>

          <p>
          <a href={{ url_for('waitlists.new') }} class="btn btn-primary">Add Waitlist</a> 
          </p>

        </div>
      </div>
    </div>


    <div class="col-md-3 col-sm-6 hero-feature">
      <div class="thumbnail">
        <img src="" alt="" height="400" width="420">
        <div class="caption">
          <h3>Show Waitlist </h3>
          <p>
          <a href={{ url_for('waitlists.index') }} class="btn btn-primary">Display</a> 
          </p>
        </div>
      </div>
    </div>

  </div>
  <!-- /.row -->


</header>
{% endblock %}

app/templates/layout.html
<!doctype html>
<title>Waiting List</title>

<link href= "static/css/login.css" rel="stylesheet">
<div class=page>
  <h1>Waiting List</h1>
  <div class=metanav>
  {% if not session.logged_in %}
    <a href="{{ url_for('auth.login') }}">log in</a>
  {% else %}
    <a href="{{ url_for('auth.logout') }}">log out</a>
  {% endif %}
  </div>
  {% for message in get_flashed_messages() %}
    <div class=flash>{{ message }}</div>
  {% endfor %}
  {% block body %}{% endblock %}
</div>

app/templates/restaurantlist2.html
{% extends "mainlayout.html" %}
{% block content %}
<h2 align="center"> Restaurant Information </h2>
<div class="table-responsive-vertical shadow-z-1">
  <!-- Table starts here -->
  <table id="table" class="table table-hover table-mc-light-blue">
    <thead>
      <tr>
        <th><b>Restaurant_ID</b></th>
        <th><b>Restaurant_Name</b></th>
        

      </tr>
    </thead>
    <tbody>

      {% for row in rows %}
      <tr>
        <td>{{row[0]}}</td>
        <td>{{row[1]}}</td>
     


        <td>

          <form action="{{ url_for('deleterestaurant') }}" method=post class=deleterestaurant>
            <input type = hidden name = "restaurant_id" value = "{{row[0]}}"/>
            <input type=submit value = Delete></input>
          </form>




        </td>

        <td>

          <form action="{{ url_for('updaterestaurant') }}" method=post class=updaterestaurant>
            <input type = hidden name = "old_id" value = "{{row[0]}}"/>
            <input type=submit value = Update></input>
          </form>


        </td>

        
      </tr>
      {% endfor %}

    </tbody>
  </table>
</div>  
{% endblock %}

app/templates/result.html
{% extends "layouts/base.html" %}
{% block content %}
<!-- Jumbotron Header -->
<header class="jumbotron hero-spacer">
  <h1 align= "center">  result of addition : </h1>
  <h1 align= "center"> {{ msg }} </h1>
  <p align="center"><a  href= "{{ url }}" class="btn btn-primary btn-large"> Go back to homepage</a>
  </p>
</header>
<hr>
<hr>
<!-- Footer -->
<footer>
  <div class="row">
    <div class="col-lg-12">
      <p>Copyright &copy; Your Website 2014</p>
    </div>
  </div>
</footer>
{% endblock %}

app/templates/tablelist.html
{% extends "mainlayout.html" %}
{% block content %}
<h2 align="center"> Table Information </h2>
<div class="table-responsive-vertical shadow-z-1">
  <!-- Table starts here -->
  <table id="table" class="table table-hover table-mc-light-blue">
    <thead>
      <tr>
        <th><b>Restaurant_ID </b></th>
        <th><b>Restaurant_name</b></th>
        <th><b>Table_ID</b></th>
        <th><b> Seats</b></th>

      </tr>
    </thead>
    <tbody>

      {% for row in rows %}
      <tr>
        <td>{{row[0]}}</td>
        <td>{{row[1]}}</td>
        <td> {{row[2]}}</td>
        <td> {{row[3]}}</td>


        <td>

          <form action="{{ url_for('deletetable') }}" method=post class=deletetable>
            <input type = hidden name = "table_id" value = "{{row[2]}}"/>
            <input type=submit value = Delete></input>
          </form>


        </td>

        <td>
          <form action="{{ url_for('updatetable') }}" method=post class=updatetable>
             <input type = hidden name = "old_id" value = "{{row[2]}}"/>
            <input type=submit value = Update></input>
          </form>


        </td>

      </tr>
      {% endfor %}

    </tbody>
  </table>
</div>  
{% endblock %}

app/templates/updaterestaurant.html
{% extends "mainlayout.html" %}
{% block content %}
<form action = "{{ url_for('addrecupdaterestaurant') }}" method = "POST">
  <h3>Enter Customer Information</h3>

  <input type = hidden name = "old_id" value = "{{old_id}}"/>

  Restaurant_ID<br>
  <input type = "INT" name = "update_id" /><br>

  Resturant_name<br>
  <input type = "text" name = "name" /></br>

  
  <input type = "submit" value = "submit" /><br>
</form>

{% endblock %}

app/templates/waitlist.html
{% extends "layouts/base.html" %}
{% block content %}
<div class="row text-center">

  <div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
      <img src="" alt="" height="400" width="420">
      <div class="caption">
        <h3>Add new party</h3>

        <p>
        <a href={{ url_for('party.new') }} class="btn btn-primary">Add Party</a> 
        </p>

      </div>
    </div>
  </div>


  <div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
      <img src="" alt="" height="400" width="420">
      <div class="caption">
        <h3>Show Party Information</h3>
        <p>
        <a href={{ url_for('party.index') }} class="btn btn-primary">Display</a> 
        </p>
      </div>
    </div>
  </div>

</div>
<!-- /.row -->


<!-- Page Features -->
<div class="row text-center">

  <div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
      <img src="" alt="" height="400" width="420">
      <div class="caption">
        <h3>Add new Notification</h3>

        <p>
        <a href={{ url_for('new_notification') }} class="btn btn-primary">Add Notification</a> 
        </p>

      </div>
    </div>
  </div>


  <div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
      <img src="" alt="" height="400" width="420">
      <div class="caption">
        <h3>Show Notification Information</h3>
        <p>
        <a href="notifications" class="btn btn-primary">Display</a> 
        </p>
      </div>
    </div>
  </div>

</div>
{% endblock %}